import { createSlice, nanoid } from "@reduxjs/toolkit";

// Define the initial state of the todo slice
const initialState = {
    todos: []
}

// Create a todo slice with reducers
const todoSlice = createSlice({
    name: "todo",
    initialState,
    reducers: {
         // Reducer function to add a new todo
        addTodo: (state, action) => {
            // Create a new todo object with a unique id generated by nanoid
            const todo = {
                id: nanoid(),
                text: action.payload,
                isComplete: true
            }
            state.todos.push(todo)
        },

        // Reducer function to remove a todo
        removeTodo: (state, action) => {
            state.todos = state.todos.filter((todo) => todo.id != action.payload);
        },

          // Reducer function to toggle the completion status of a todo
        toggleCompleted: (state, action) => {
            const { id } = action.payload;
            
            // Map over the todos array and toggle the isComplete property of the todo with the specified id
            state.todos = state.todos.map(todo => {
                if (todo.id === action.payload) {
                    return {
                        ...todo,
                        isComplete: !todo.isComplete 
                    };
                }
                
                return todo;
            });
        }
    }
});

export const { addTodo, removeTodo, toggleCompleted } = todoSlice.actions

export default todoSlice.reducer;